import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NaveBar from "./common/navbar";
import { ReduxProvider } from "@/store/reduxProvider";
import Footer from "./common/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" precedence="default" />
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" precedence="default" />
      
      <body className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning>
        <NaveBar/>
        <ReduxProvider>
        {children}
        </ReduxProvider>
        <Footer />
      </body>
    </html>
  );
}
